<?php
	$article 			= $this->article;
	$articleAttributes	= $this->articleAttributes;
	$tags 				= ""; 

	// If $article is false => Article does not exist.
	if(!$article) {
		$error = '
			<div class="alert alert-danger alert-error show-validation-error">
				Sorry! The article you are searching for does not exist.
			</div>';
		
		echo $error;
		return;
	}

	foreach ($articleAttributes as $attr) {
		if("1"==$attr->attr_id) {
			$tags 	.= $attr->value.",";
		}
	}
?>

<?php
	echo $this->headScript()->appendFile($this->baseUrl().'/js/tag-it-js/tag-it.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/tag-it-css/jquery.tagit.css');
	
	echo $this->headScript()->appendFile($this->baseUrl().'/js/article.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/article.css');
?>

<!-- Article Title goes in the button below -->
<button class="btn btn-default btn-lg disabled btn-block"><span class="glyphicon glyphicon-plus"></span> <?= $article->title;?></button><br>

<!-- Article Image goes below -->
<div class = "article-img">
	<?php echo "<img class='img-rounded 'src = '".$this->baseUrl()."/img/default/default.jpg"."' />" ;?>
</div><br>

<!-- Social Share Links	 -->
<div class = "pull-right social-share-containter">
	<div class = "social-share" >
		<div class = 'social-share-facebook'> 
			Share on Facebook : <img src = '/img/facebook-icon.png' class = 'img-circle' height = '20' widht = '20' alt = 'Share on Facebook' >
		</div>
	</div>
</div>

<input id="hidden-tags" type="hidden" value="<?= $tags; ?>"/>
<input id="hidden-article-id" type="hidden" value="<?= $article->id; ?>"/>

<!-- Its important to add tags, or else the tags do not list out as tags. -->
<ul id="readOnlyTags" ><li></li></ul>

<!-- Article Text goes below -->
<div class = "article-description"><?= $article->article_text; ?></div>

<!-- Add Article Form, Initially hidden, Toggle on #add-comment-button click -->
<form id = "add-comment-form-0"><hr>
	<textarea id = "comment-textarea-0" ></textarea>
	<button id = "post-comment-button-0" class="post-comment-button btn btn-primary">Post</button>
	<button id = "cancel-comment-button-0" class="cancel-comment-button btn btn-default">Cancel</button>
</form>
<br>
<button id = "add-comment-button" class="btn btn-primary btn-lg btn-block">Add Comment <span class="glyphicon glyphicon-comment"></span></button>

<div id = "view-comments-div"></div>