<?php
	echo $this->headScript()->appendFile($this->baseUrl().'/js/tag-it-js/tag-it.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/tag-it-css/jquery.tagit.css');
?>
<br></br>
<button class="btn btn-default btn-lg disabled btn-block"><span class="glyphicon glyphicon-plus"></span> New Article</button><br>

<form class = "form-horizontal" method = "POST">
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="title">Title : <span class="glyphicon glyphicon-pencil"> </label>
		<div class = "col-xs-6">
			<input class="form-control" type ="text" id="inputTitle" placeholder = "Title"></input> 
		</div>
	</div>
	
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="Upload">Upload : <span class="glyphicon glyphicon-upload"> </label>
		<div class = "col-xs-6">
		<!-- <input class="form-control" type ="text" id="inputUpload" placeholder = "Upload Images"></input> -->
				<span class="btn btn-default btn-file"> Browse <input type="file"> </span> 
		</div>
	</div>

	<div class = "form-group">
		<label class="control-label col-xs-3" for ="Description">Description : <span class="glyphicon glyphicon-align-justify"> </label>
		<div class = "col-xs-6">
			<textarea class="form-control" id="inputDescription" placeholder = "Description (optional)" rows = "8" ></textarea> 
		</div>
	</div>

	<div class = "form-group">
		<label class="control-label col-xs-3" for ="tags">Tags : <span class="glyphicon glyphicon-tags"> </label>
		<div class = "col-xs-6">
			<ul id="myTags"></ul>
		</div>
	</div>

	<button id="create-article" class="btn btn-primary btn-lg active btn-block"><span class="glyphicon glyphicon-send"></span> Create New Article</button>

</form>