
<!-- JavaScript and CSS Start-->
<script type="text/javascript" src="/js/new-article.js"></script>
<link href="/css/new-article.css" media="screen" rel="stylesheet" type="text/css" >

<script type="text/javascript" src="/js/tag-it-js/tag-it.js"></script>
<link href="/css/tag-it-css/jquery.tagit.css" media="screen" rel="stylesheet" type="text/css" ><script 

<script type="text/javascript" src="/js/text-editor-plugin/jquery.classyedit.js"></script><link href="/css/new-article.css" media="screen" rel="stylesheet" type="text/css" >
<link href="/css/text-editor-plugin/jquery.classyedit.css" media="screen" rel="stylesheet" type="text/css" ><br></br>

<!-- For classy text editor -->
<script>
	$(document).ready(function() {
	    $(".classy-editor").ClassyEdit();
	});
</script>
<!-- JavaScript and CSS End-->

<br></br>

<button class="btn btn-default btn-lg disabled btn-block"><span class="glyphicon glyphicon-plus"></span> New Article</button><br>

<!-- Validation Errors -->
<div class="alert alert-danger alert-error show-validation-error"></div>

<!-- Success Message -->
<div class="alert alert-success show-validation-success"></div>

<!-- New Article Form -->
<form class = "form-horizontal new-article-form" id = "new-article-from" method = "POST" enctype = "multipart/form-data">
	<!-- Title -->
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="title">Title : <span class="glyphicon glyphicon-pencil"> </label>
		<div class = "col-xs-6">
			<input class="form-control" type ="text" id="inputTitle" placeholder = "Title"></input> 
		</div>
	</div>
	
	<!-- Upload -->
	<!-- <div class = "form-group">
		<label class="control-label col-xs-3" for ="Upload">Upload : <span class="glyphicon glyphicon-upload"> </label>
		<div class = "col-xs-6">
		<input class="form-control" type ="file" id="inputUpload" placeholder = "Upload Images"></input>
		</div>
	</div> -->
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="Upload">Upload : <span class="glyphicon glyphicon-upload"> </label>
		<div class = "col-xs-6">
		<input class="form-control" type ="file" id="FileInput" name="FileInput" placeholder = "Upload Images"></input>
		</div>
	</div>

	<!-- Description -->
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="Description">Description : <span class="glyphicon glyphicon-align-justify"> </label>
		<div class = "col-xs-6">
			<textarea class = "form-control classy-editor" id = "inputDescription" placeholder = "Description (optional)"></textarea> 
		</div>
	</div>

	<!-- Tags -->
	<div class = "form-group">
		<label class="control-label col-xs-3" for ="tags">Tags : <span class="glyphicon glyphicon-tags"> </label>
		<div class = "col-xs-6">
			<ul id="article-tags"></ul>
		</div>
	</div>
	<input type = "hidden" name="tags" id="all-tags" disabled="true"> 

	<button id="create-article" class="btn btn-primary btn-lg active btn-block"><span class="glyphicon glyphicon-send"></span> Create New Article</button>

	<input type = "submit" id = "submit-new-article-form" />
</form>

<div id = "output"></div>