<!-- 
Top-Fixed Navigation Bar.
-->

<div class = "container">
	<div class = "navbar navbar-inverse navbar-fixed-top">
		<div class = "container">
			<div class = "navbar-header">
				<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = ".navbar-collapse" >
					<span class = "icon-bar"></span>
					<span class = "icon-bar"></span>
					<span class = "icon-bar"></span>
				</button>
				<a href = "/" class = "navbar-brand">IT'S INTERESTING!!</a>
			</div> <!-- End .navbar-header -->
			
			<div class = "navbar-collapse collapse navbar-right">
				<ul class = "nav navbar-nav">
					<li><a href = "#" id="signup-header-login">LOG IN</a></li>
					<li><a href = "/User/new">SIGN UP</a></li>
				</ul>					
			</div> <!-- End .navbar-collapse collapse -->
		</div> <!-- End .Container-->
	</div> <!-- End .navbar navbar-default navbar-fixed-top -->

	<div class = "navbar navbar-inverse" id = "signup-header-login-form-div">
		<div class = "container">
			<input type="text"/>
		</div> <!-- End .Container-->
	</div> <!-- End .navbar navbar-default navbar-fixed-top -->
</div> <!-- End .Container-->
