<br /><br />
<?php
	echo $this->headScript()->appendFile($this->baseUrl().'/js/home.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/home.css');

	$userInfo 	= $this->userInfo;
	$articles 	= $this->articles;
?>
<!-- Share Something Interesting Button-->
<a href="/Article/new" class="btn btn-default btn-info btn-lg btn-block">
	<span class="glyphicon glyphicon-plus"></span> 
	Share Something Interesting
</a>
<!-- Search Something Interesting By Tag -->

<!-- List Articles -->
<?php
		
	echo "<hr><div class = 'container'>";
		echo "<div class = 'row'>";
			foreach ($articles as $article) {
				createArticleThumbnail($article);
			}
		echo "</div>";
	echo "</div>";

	function createArticleThumbnail($article){
		$th 	 = "";
		$th 	.=	"<div class = 'col-md-3'>";
		$th 	.=		"<div class = 'thumbnail article_thumbnail' id = article_thumbnail_".$article->id.">";
		$th 	.=			"<img src = '/img/default/default.jpg"."' />";
		$th 	.=			"<div class = 'caption'>";
		$th 	.=				"<h3>".$article->title."</h3>";
		$th 	.=				"<p>".$article->article_text."</p>";
		$th 	.=			"</div>";
		$th 	.=		"</div>";
		$th 	.=	"</div>";

		echo $th;
	}
?>