<br /><br />
<?php
	// echo $this->headScript()->appendFile($this->baseUrl().'/js/home.js');
	echo "<script src='".$this->baseUrl()."/js/home.js'></script>";
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/home.css');

	echo $this->headScript()->appendFile($this->baseUrl().'/js/tag-it-js/tag-it.js');
	echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/tag-it-css/jquery.tagit.css');

	$userInfo 	= $this->userInfo;
?>

<!-- Share Something Interesting Button-->
<a href="/Article/new" class="btn btn-default btn-info btn-lg btn-block">
	<span class="glyphicon glyphicon-plus"></span> 
	Share Something Interesting
</a><br>

<!-- Search Something Interesting By Tag -->
<div class = "form-group">
	<label class="control-label col-xs-1" for ="tags">Tags : <span class="glyphicon glyphicon-tags"> </label>
	<div class = "col-xs-10">
		<ul id="article-tags"></ul>
	</div>
	<div class = "col-xs-1 pull-left">
		<button id="search-by-tags" class="btn btn-default btn-info btn-block active "><span class="glyphicon glyphicon-search"></span></button>
	</div>

</div>
<input type = "hidden" name="tags" id="all-tags" disabled="true"> 
<br><hr>	

<div class = "col-lg-9 searched-articles-list">
	<!-- List Articles -->
	<div class = 'row searched-articles-list-row'>
		<!-- Articles will show up in the searched-articles-list-row div -->
	</div> 
</div>

<!-- Side Bar -->
<div class = "col-lg-3">
	<div class ="list-group">

		<!-- Popular tags -->
		<div class = "list-group-item">
			<h4 class = "list-group-item-heading" >Popular Tags</h4>
			<p class = "list-group-item-text" >Most popular tags will go here</p>
		</div>
		<br>

		<!-- Popular Articles -->
		<div class = "list-group-item">
			<h4 class = "list-group-item-heading" >Popular Articles</h4>
			<p class = "list-group-item-text" >Most Popular articles will go here</p>
		</div>
	</div>
</div>